# vim: syntax=python tabstop=4 expandtab
# coding: utf-8

__author__ = "Patrik Smeds"
__copyright__ = "Copyright 2021, Patrik Smeds"
__email__ = "patrik.smeds@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/mutect2.smk"
include: "rules/vardict.smk"
include: "rules/freebayes.smk"
include: "rules/tabix_vcf.smk"
include: "rules/merge_vcf.smk"
include: "rules/bgzip_vcf.smk"
include: "rules/filter_vcf_on_format.smk"
include: "rules/decompose.smk"
include: "rules/normalize.smk"
include: "rules/sort_vcf.smk"


ruleorder: mutect2 > tabix_vcf


report: "report/workflow.rst"


rule all:
    input:
        unpack(compile_output_list),
