__author__ = "Patrik Smeds"
__copyright__ = "Copyright 2021, Patrik Smeds"
__email__ = "patrik.smeds@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/merge_af_complex_variants.smk"
include: "rules/bcbio_variation_recall.smk"
include: "rules/bcftools.smk"
include: "rules/bed_split.smk"
include: "rules/bgzip.smk"
include: "rules/deeptrio.smk"
include: "rules/deepvariant.smk"
include: "rules/fix_af.smk"
include: "rules/freebayes.smk"
include: "rules/gatk.smk"
include: "rules/glnexus.smk"
include: "rules/haplotypecaller.smk"
include: "rules/mutect2_pass_filter.smk"
include: "rules/tabix.smk"
include: "rules/vardict.smk"
include: "rules/vt.smk"


ruleorder: bcbio_variation_recall_ensemble > bgzip
ruleorder: bcftools_sort > bgzip
ruleorder: bcftools_view > bgzip
ruleorder: gatk_mutect2 > bgzip
ruleorder: gatk_mutect2 > tabix
ruleorder: gatk_mutect2_gvcf > bgzip
ruleorder: gatk_mutect2_gvcf > tabix
ruleorder: gatk_mutect2_filter > bgzip
ruleorder: mutect2_pass_filter > bgzip
ruleorder: vt_decompose > bgzip
ruleorder: vt_normalize > bgzip


rule all:
    input:
        unpack(compile_output_list),
