__author__ = "Patrik Smeds"
__copyright__ = "Copyright 2021, Patrik Smeds"
__email__ = "patrik.smeds@scilifelab.uu.se"
__license__ = "GPL-3"


include: "rules/common.smk"
include: "rules/bcbio_variation_recall.smk"
include: "rules/bcftools.smk"
include: "rules/bed_split.smk"
include: "rules/bgzip.smk"
include: "rules/fix_af.smk"
include: "rules/freebayes.smk"
include: "rules/mutect2.smk"
include: "rules/tabix.smk"
include: "rules/vardict.smk"
include: "rules/vt.smk"


ruleorder: mutect2 > mutect2_gvcf > tabix


rule all:
    input:
        unpack(compile_output_list),
