$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: fasta reference file
    required:
      - fasta

  mutect2:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for mutect2
      container:
        type: string
        description: name or path to docker/singularity container
      params:
        type: object
        properties:
          extra:
            type: string
            description: parameters that should be forwarded to mutect2

  freebayes:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for freebayes
      container:
        type: string
        description: name or path to docker/singularity container
      params:
        type: object
        properties:
          extra:
            type: string
            description: parameters that should be forwarded to freebayes

  tabix_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for tabix_vcf
      container:
        type: string
        description: name or path to docker/singularity container
      params:
        type: object
        properties:
          extra:
            type: string
            description: parameters that should be forwarded to tabix_vcf

  filter_vcf_on_format:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for filter_vcf_on_format
      container:
        type: string
        description: name or path to docker/singularity container
      params:
        type: object
        properties:
          extra:
            type: string
            description: extra parameters that should be forwarded to filter_vcf_on_format
          filter:
            type: string
            description: filter parameters that should be forwarded to filter_vcf_on_format

  bgzip_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for bgzip
      container:
        type: string
        description: name or path to docker/singularity container

  merge_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for merge_vcf
      container:
        type: string
        description: name or path to docker/singularity container
      input:
        type: object
        properties:
          skip_chrs:
            type: list
            description: list of chromosomes to skip
      params:
        type: object
        properties:
          extra:
            type: string
            description: parameters that should be forwarded to merge_vcf

  vardict:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for vardict
      container:
        type: string
        description: name or path to docker/singularity container
      params:
        type: object
        properties:
          extra:
            type: string
            description: parameters that should be forwarded to vardict
          bed_columns:
            type: string
            description: columns to use in bed file
          allele_frequency_threshold:
            type: string
            description: allele frequency threshold

  decompose:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for decompose
      container:
        type: string
        description: name or path to docker/singularity container

  normalize:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for normalize
      container:
        type: string
        description: name or path to docker/singularity container

  sort_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for sort_vcf
      container:
        type: string
        description: name or path to docker/singularity container

  required:
    - samples
    - units
    - reference
    - resources
    - default_container
