$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:

  resources:
    type: string
    description: path to resources.yaml file

  samples:
    type: string
    description: path to samples.tsv file

  units:
    type: string
    description: path to units.tsv file

  reference:
    type: object
    properties:
      design_bed:
        type: string
        description: path to panel design bed file
      fasta:
        type: string
        description: path to reference fasta file
      fai:
        type: string
        description: path to reference fasta index file
      skip_chrs:
        type: array
        description: list of chromosomes that should be skipped
        items:
            type: string
    required:
      - design_bed
      - fasta
      - fai

  default_container:
    type: string
    description: name or path to a default docker/singularity container

  bcbio_variation_recall_ensemble:
    type: object
    description: parameters for bcbio_variation_recall_ensemble
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      callers:
        type: array
        description: list of callers that are included in the ensemble vcf in sort order
        items:
            type: string
      container:
        type: string
        description: name or path to docker/singularity container
      support:
        type: integer
        description: number of callers to support variant to be included in ensemble vcf
    required:
      - callers

  bcftools_concat:
    type: object
    description: parameters for bcftools_concat
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  bcftools_sort:
    type: object
    description: parameters for bcftools_sort
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

  bcftools_view:
    type: object
    description: parameters for bcftools_view
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  bed_split:
    type: object
    description: parameters for bed_split
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

  bgzip:
    type: object
    description: parameters for bgzip
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
  
  deeptrio_call_variants:
    type: object
    description: parameters for deeptrio_call_variants
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      model:
        type: object
        description: Path to the deepvariant model file
        properties:
          parent:
            child:
              type: string
              description: model file for child
            parent:
              type: string
              description: model file for parent
    required:
      - model

  deeptrio_make_examples:
    type: object
    description: parameters for deeptrio_make_examples
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      n_shards:
        type: integer
        description: Number of shards for deepvariant make_examples
  
  deeptrio_postprocess_variants:
    type: object
    description: parameters for deeptrio_postprocess_variants
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  deepvariant:
    type: object
    description: parameters for deepvariant
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      model_type:
        type: string
        description: Specify which model type to use with deepvariant
      output_gvcf:
        type: boolean
        description: Specify if a gVCF should be written
  
  fix_af:
    type: object
    description: parameters for fix_af
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

  freebayes:
    type: object
    description: parameters for freebayes
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_mutect2:
    type: object
    description: parameters for gatk_mutect2
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_mutect2_filter:
    type: object
    description: parameters for gatk_mutect2_filter
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_mutect2_gvcf:
    type: object
    description: parameters for gatk_mutect2_gvcf
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  gatk_mutect2_merge_stats:
    type: object
    description: parameters for gatk_mutect2_merge_stats
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

  glnexus:
    type: object
    description: parameters for gatk_mutect2_merge_stats
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded
      glnexus_config:
        type: string
        description: path to the glnexus config file
      in_gvcf:
        type: string
        description: |
          string listing the input files 
          created by the get_glnexus_input function in common.smk

  haplotypecaller:
    type: object
    description: parameters for haplotypecaller
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  merge_af_complex_variants:
    type: object
    description: parameters for merge_af_complex_variants
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      merge_method:
        type: string
        enum: ["skip", "max", "sum"]
        description: method to handle allele frequencies from complex variants,
                     skip, max or sum

  mutect2_pass_filter:
    type: object
    description: parameters for mutect2_pass_filter
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      pass_filters:
        type: array
        description: list of filter flags that are retained in the vcf
        items:
            type: string

  tabix:
    type: object
    description: parameters for tabix
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  vardict:
    type: object
    description: parameters for vardict
    properties:
      allele_frequency_threshold:
        type: string
        description: allele frequency threshold
      bed_columns:
        type: string
        description: columns to use in bed file
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded

  vt_decompose:
    type: object
    description: parameters for vt_decompose
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

  vt_normalize:
    type: object
    description: parameters for vt_normalize
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated
      container:
        type: string
        description: name or path to docker/singularity container

required:
  - default_container
  - reference
  - resources
  - samples
  - units
