name: pycodestyle

on:
  push:
    branches:
     - develop
     - master
  pull_request:
    branches:
     - develop
     - master
  workflow_dispatch:

jobs:
  pycodestyle:
    name: pycodestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      - name: Install requirements.test.txt
        run: |
          pip install -r requirements.test.txt
      - name: Check python syntax lib
        run: pycodestyle --max-line-length=130 --statistics workflow/scripts
      - name: Check python syntax unit tests
        run: pycodestyle --max-line-length=130 --statistics .tests/units
