from hydra_genetics.utils.resources import load_resources


rule all:
    input:
        "snv_indels/bcbio_variation_recall_ensemble/NA12878_N.ensembled.vcf.gz",
        "snv_indels/mutect2_gvcf/NA12878_N.merged.g.vcf.gz",


configfile: "config.yaml"


config = load_resources(config, config["resources"])


def extract_module_version_from_readme(modulename):
    search_string = modulename + ":(.+)\n$"
    with open("../../README.md", "r") as reader:
        for line in reader:
            result = re.search(search_string, line)
            if result:
                return result[1]


module alignment:
    snakefile:
        github(
            "hydra-genetics/alignment",
            path="workflow/Snakefile",
            tag=extract_module_version_from_readme("alignment"),
        )
    config:
        config


use rule * from alignment as alignment_*


module snv_indels:
    snakefile:
        "../../workflow/Snakefile"
    config:
        config


use rule * from snv_indels as snv_indels_*
